### 📚 Importing Libraries

In this section, we import the essential libraries for our project. 

- `TensorFlow` is used to build and train deep learning models.
- `Pandas` helps in data processing and analysis.

Let's get started! 🚀


In [1]:
import tensorflow as tf
import pandas as pd

### 🔢 Defining and Exploring Tensors

In this cell, we define various types of tensors using `tf.constant` in TensorFlow:

- **Scalar**: A single constant value.
- **Vector**: A one-dimensional array.
- **Matrix**: A two-dimensional array.
- **Higher-Dimensional Tensor**: A 3D tensor to represent more complex data.

We then create a function `f` that retrieves different properties of each tensor, such as:

- **Shape** 🧩: The dimensions of the tensor.
- **Rank** 📏: The number of dimensions.
- **NDIM** 🧮: Another way to describe the dimensions.
- **Size** 📐: The total number of elements.
- **DType** 🏷️: The data type of the tensor elements.

Finally, we display these properties in a DataFrame for easy comparison. 🧐



In [2]:
scaler = tf.constant(1)
vector = tf.constant([1, 2, 3, 4, 5], dtype=tf.float16)
metrix = tf.constant([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]], name='metrix')

tensor = tf.constant(
    [
        [
            [1, 2, 3],
            [4, 5, 6],
        ],
        [
            [7, 8, 9],
            [10, 11, 12],
        ],
        [
            [13, 14, 15],
            [16, 17, 18],
        ],
    ]
)

f = lambda x: [x.shape, tf.rank(x).numpy(), x.ndim, tf.size(x).numpy(), x.dtype]

lst = [f(scaler), f(vector), f(metrix), f(tensor)]
pd.DataFrame(lst, columns=['shape','rank', 'ndim' , 'size', 'dtype'])

shape  rank  ndim  size               dtype
0         ()     0     0     1    <dtype: 'int32'>
1        (5)     1     1     5  <dtype: 'float16'>
2     (3, 3)     2     2     9    <dtype: 'int32'>
3  (3, 2, 3)     3     3    18    <dtype: 'int32'>

### 🔄 Constant vs Variable in TensorFlow

In this cell, we explore the difference between `tf.constant` and `tf.Variable`:

- **`tf.constant`**: Defines an immutable tensor, meaning its values cannot be changed after creation.
- **`tf.Variable`**: Defines a mutable tensor, which can be updated during the program's execution.

By printing `v1` and `v2`, we can see both tensors and understand how they differ in behavior. 📊



In [3]:
v1 = tf.constant([1, 2, 3, 4])
v2 = tf.Variable([1, 2, 3, 4])
v1, v2

(<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>)

### ✏️ Modifying Elements in a TensorFlow Variable

Here, we demonstrate how to modify a specific element in a `tf.Variable` tensor. 

- Using the `assign` method, we update the second element of `v2` to 23.
- This highlights the mutability of `tf.Variable`, allowing for in-place updates, which is not possible with `tf.constant`.

Let's see the updated `v2` tensor below. 🔄



In [4]:
v2[1].assign(23)
v2

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([ 1, 23,  3,  4], dtype=int32)>

### 🔍 Finding Max and Min Elements in a Tensor

In this cell, we use `tf.argmax` and `tf.argmin` to find the indices of the maximum and minimum values in the `v2` tensor. 

- **`tf.argmax(v2)`** returns the index of the maximum value.
- **`tf.argmin(v2)`** returns the index of the minimum value.

We then use these indices to retrieve the actual maximum and minimum values from `v2`. This is useful for identifying extreme values in a tensor. 📈📉



In [5]:
max_index = tf.argmax(v2)
min_index = tf.argmin(v2)
v2[max_index], v2[min_index]

(<tf.Tensor: shape=(), dtype=int32, numpy=23>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>)

### 🎲 Generating Random Numbers with TensorFlow and Using Seed for Reproducibility

In these cells, we demonstrate how to generate random numbers using TensorFlow and the concept of *seeding* to ensure reproducibility.

1. **Using `tf.random.Generator`**: 
   - We create a random generator with a specific seed and generate random values with a normal distribution.

2. **Using `tf.random.set_seed`**: 
   - This sets the seed for all random operations in TensorFlow, ensuring that subsequent random numbers are reproducible.
   - We generate a random 3x3 integer array with values between 0 and 100.

3. **Reusing `tf.random.Generator` with Seed**:
   - We use the generator with a seed again to create a random integer tensor.
   
Setting a seed allows us to achieve the same random output each time we run the code, which is helpful for debugging and consistency. 🔒



In [6]:
gen = tf.random.Generator.from_seed(42)
gen.normal((3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ],
       [ 0.09988727, -0.50998646, -0.7535805 ]], dtype=float32)>

In [7]:
tf.random.set_seed(42)
tf.random.uniform((3, 3),minval=0, maxval=100, dtype=tf.int32, seed=42)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[33, 38, 30],
       [74,  8, 41],
       [53, 73, 42]], dtype=int32)>

In [8]:
gen = tf.random.Generator.from_seed(42)
gen.uniform((3, 3), minval=0, maxval=100, dtype=tf.int32)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 3, 97, 26],
       [98, 26, 81],
       [71, 27, 42]], dtype=int32)>

**Converting `metrix` to NumPy**:
   - We use the `.numpy()` method to convert the `metrix` tensor into a NumPy array, which is helpful when working with NumPy operations.

In [9]:
metrix.numpy()

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

**Shuffling Rows with `tf.random.shuffle`**:
   - We apply `tf.random.shuffle` to randomly shuffle the rows of the `metrix` tensor.
   - By setting a seed, we ensure reproducibility, meaning the shuffling will be the same each time we run the code.

These steps help in understanding data transformations between TensorFlow and NumPy, and how we can control randomness in TensorFlow. 🎲


In [10]:
tf.random.shuffle(metrix, seed=42)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

**Using `tf.ones`**:
   - We create a 3x5 tensor filled with ones.
   - The data type is set to `int8`, showing that we can specify the type of the tensor elements.


In [11]:
tf.ones(shape=(3, 5), dtype=tf.int8)

<tf.Tensor: shape=(3, 5), dtype=int8, numpy=
array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)>

**Using `tf.zeros`**:
   - We create a 3x3 tensor filled with zeros.
   - The default data type here is `float32`.

In [12]:
tf.zeros(shape=(3, 3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

### 🔄 Adding Dimensions to Tensors

In this cell, we demonstrate three different ways to add a new dimension to the `tensor`:

1. **Using `tf.newaxis` in indexing**:
   - We add a new axis at the last position, increasing the tensor's dimensionality.

2. **Using `tf.newaxis` within specific positions**:
   - By inserting `tf.newaxis` between dimensions, we control exactly where the new axis is added.

3. **Using `tf.expand_dims`**:
   - This function allows us to add a new dimension at the specified `axis` position, providing a flexible way to reshape tensors.

These techniques are essential for manipulating tensor shapes to make them compatible with various machine learning models. 📏


In [13]:
print(tensor[..., tf.newaxis].shape)
print(tensor[:, :, tf.newaxis, :].shape)
print(tf.expand_dims(tensor, axis=2).shape)

(3, 2, 3, 1)
(3, 2, 1, 3)
(3, 2, 1, 3)


### ➕ Basic Arithmetic Operations on Tensors

In this cell, we perform various mathematical operations on the tensor `a`:

1. **Addition with `tf.add`**:
   - We add `a` to itself, resulting in each element being doubled.

2. **Subtraction with `tf.subtract`**:
   - We subtract `a` from itself, which results in a tensor of zeros.

3. **Multiplication with `tf.multiply`**:
   - We multiply `a` by itself, squaring each element.

These operations demonstrate how to perform basic arithmetic in TensorFlow, which is essential for data processing and machine learning tasks. 🔢


In [14]:
a = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

print(tf.add(a, a).numpy())
print(tf.subtract(a, a).numpy())
print(tf.multiply(a, a).numpy())

[[ 2  4]
 [ 6  8]
 [10 12]]
[[0 0]
 [0 0]
 [0 0]]
[[ 1  4]
 [ 9 16]
 [25 36]]


### 🔄 Reshaping and Transposing Tensors

In this cell, we apply reshaping and transposing operations on the tensor `a`:

1. **Reshape with `tf.reshape`**:
   - We reshape `a` to a new shape (2, 3). This changes the organization of elements without altering the data.

2. **Transpose with `tf.transpose`**:
   - We transpose `a`, swapping rows and columns, which is useful for adjusting data orientation.

These operations are essential for organizing data in the right format, especially for feeding it into machine learning models. 📐

In [15]:
a, tf.reshape(a, (2, 3)), tf.transpose(a)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>)

### 🔗 Matrix Multiplication with Different Methods

In this cell, we perform matrix multiplication between `a` and its transpose using three different methods:

1. **Using `tf.matmul`**:
   - This is the standard method for matrix multiplication in TensorFlow.

2. **Using the `@` operator**:
   - A shorthand syntax for matrix multiplication, making the code more concise.

3. **Using `tf.tensordot`**:
   - By setting `axes=1`, we achieve matrix multiplication. This function is more versatile and can be used for dot products along specific axes.

All three methods provide the same result, and you can choose one based on readability or specific needs. 📊



In [16]:
tf.matmul(a, tf.transpose(a)),\
a @ tf.transpose(a), \
tf.tensordot(a, tf.transpose(a), axes=1)


(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 5, 11, 17],
        [11, 25, 39],
        [17, 39, 61]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 5, 11, 17],
        [11, 25, 39],
        [17, 39, 61]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 5, 11, 17],
        [11, 25, 39],
        [17, 39, 61]], dtype=int32)>)

### 📊 Basic Statistical and Mathematical Operations on Tensors

In this cell, we perform various statistical and mathematical operations on the tensor `a`:

1. **Mean (`tf.reduce_mean`)**: Calculates the average of all elements.
2. **Max & Min (`tf.reduce_max` & `tf.reduce_min`)**: Finds the maximum and minimum values.
3. **Sum (`tf.reduce_sum`)**: Computes the sum of all elements.
4. **Standard Deviation (`tf.math.reduce_std`)**: Calculates the standard deviation (casting to `float16` for precision).
5. **Square (`tf.square`)**: Squares each element in the tensor.
6. **Square Root (`tf.sqrt`)**: Computes the square root of each element (casting to `float16` for compatibility).

These functions help us derive essential statistics and perform fundamental operations on tensor data. 🧮



In [17]:
print(f'mean : {tf.reduce_mean(a).numpy()}')
print(f'max : {tf.reduce_max(a).numpy()}')
print(f'min : {tf.reduce_min(a).numpy()}')
print(f'sum : {tf.reduce_sum(a).numpy()}')
print(f'std : {tf.math.reduce_std(tf.cast(a, tf.float16)).numpy()}')
print(f'square : {tf.square(a).numpy()}')
print(f'sqrt : {tf.sqrt(tf.cast(a, tf.float16)).numpy()}')

mean : 3
max : 6
min : 1
sum : 21
std : 1.7080078125
square : [[ 1  4]
 [ 9 16]
 [25 36]]
sqrt : [[1.    1.414]
 [1.732 2.   ]
 [2.236 2.45 ]]


### 🔄 Casting Tensor Data Type

In this cell, we create a 3x3 tensor of ones using `tf.ones` and then cast its data type to `float16` using `tf.cast`. Changing the data type can be useful for compatibility with specific models or operations that require a certain precision level. 🎯



In [18]:
one = tf.ones((3,3))
tf.cast(one, dtype=tf.float16)

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float16)>

### 📏 Squeezing Tensor Dimensions

Here, we create a multi-dimensional random tensor with the shape `(2,1,2,3,1,1,3,1)` using `tf.random.uniform`. Then, we use `tf.squeeze` to remove all singleton dimensions (dimensions with size 1). This operation simplifies the tensor's shape, making it easier to work with. 🎈



In [19]:
t = tf.random.uniform(shape=(2,1,2,3,1,1,3,1))
tf.squeeze(t).shape

TensorShape([2, 2, 3, 3])

### 🔢 One-Hot Encoding with Custom Values

In this cell, we use `tf.one_hot` to perform one-hot encoding on a list `[1, 2, 1]`:

- **`depth=5`**: Specifies that each one-hot vector will have 5 elements.
- **`on_value=5`**: Sets the value for active (hot) positions to 5.
- **`off_value=0`**: Sets the value for inactive (cold) positions to 0.

One-hot encoding is commonly used for categorical data representation. This custom one-hot encoding allows for flexibility in choosing on/off values. 🌟



In [20]:
tf.one_hot([1, 2, 1], depth=5, on_value=5, off_value=0)

<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[0, 5, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 5, 0, 0, 0]], dtype=int32)>

### 🚀 This Notebook Will Be Updated! 

This is just the beginning! Stay tuned for updates as we dive deeper into TensorFlow and explore more advanced techniques. 

If you found this notebook helpful (or even mildly entertaining 😉), please don't forget to give it an upvote! 👍

Happy coding, and remember – we're all just tensors trying to find our way in the vast matrix of life! 😄

